### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by newerkartwii** [riidefi/mkw#104]
**I have followed the tutorial and installed everything (except CodeWarrior compilers bc i cant find them). When building, i get this error.**

`Traceback (most recent call last):
  File "D:\Users\Korisnik\Documents\Wii\MKWii Mods\mkw-master\mkw-master\build.py", line 328, in <module>
    build()
  File "D:\Users\Korisnik\Documents\Wii\MKWii Mods\mkw-master\mkw-master\build.py", line 315, in build
    compile_sources()
  File "D:\Users\Korisnik\Documents\Wii\MKWii Mods\mkw-master\mkw-master\build.py", line 243, in compile_sources
    compile_queued_sources()
  File "D:\Users\Korisnik\Documents\Wii\MKWii Mods\mkw-master\mkw-master\build.py", line 175, in compile_queued_sources
    pool.map(lambda s: compile_source_impl(*s), gSourceQueue)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "D:\Users\Korisnik\Documents\Wii\MKWii Mods\mkw-master\mkw-master\build.py", line 175, in <lambda>
    pool.map(lambda s: compile_source_impl(*s), gSourceQueue)
  File "D:\Users\Korisnik\Documents\Wii\MKWii Mods\mkw-master\mkw-master\build.py", line 149, in compile_source_impl
    process = subprocess.Popen(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by Leseratte10** [comment]
Well, the compilers are needed to compile the game. You can't just leave out part of the requirements and then be surprised that it doesn't work ...
The link can be found in the Github CI config.

**Comment by newerkartwii** [comment]
wdym github ci config? where can i find it?

**Comment by terorie** [comment]
link to zip in .github/workflows/build.yml

**Comment by terorie** [comment]
@newerkartwii So did it work? :)
